### ISSUE TITLE
Make a PyPI package

### ISSUE THREAD

**Issue by vicyap** [adafruit/Adafruit_Python_BME280#15]
I think it would be nice to have this as a PyPI package. Is anyone looking into this already?

**Comment by ghost** [comment]
I second this. I'm currently trying to put together a simple Flask app in a Docker container on the Raspberry Pi and it would be very useful to be able to simply add this library to my requirements.txt file. Pretty please?

**Comment by tadas-s** [comment]
I believe [this exists now][1]. However.. Module does not seem to export constants required to run the example in the project:

```
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from Adafruit_BME280 import *

In [2]: sensor = BME280(t_mode=BME280_OSAMPLE_8, p_mode=BME280_OSAMPLE_8, h_mode=BME280_OSAMPLE_8)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-798d4be37ef3> in <module>()
----> 1 sensor = BME280(t_mode=BME280_OSAMPLE_8, p_mode=BME280_OSAMPLE_8, h_mode=BME280_OSAMPLE_8)

NameError: name 'BME280_OSAMPLE_8' is not defined
```

Project's `__init__.py`:

```python
from .BME280 import BME280
```

When it should really be something more like:

```python
from .BME280 import *
```

I'm not even sure where this is really coming from, since this project doesn't even include `__init__.py` :man_shrugging: .

[1]: https://pypi.org/project/Adafruit-BME280/

**Comment by ladyada** [comment]
closing old issues - this library has been deprecated - check out our new libary
https://learn.adafruit.com/adafruit-bme280-humidity-barometric-pressure-temperature-sensor-breakout
which has instructions that are on pypi
